x-logging: &default-logging
  driver: "fluentd"
  options:
    fluentd-address: "localhost:24224"
    fluentd-async-connect: "true"
    tag: "{{.Name}}-{{.ID}}"

services:
  ##### App1 & DAPR Sidecar #####
  app1:
    build:
      context: .
      dockerfile: ./apps/app1/Dockerfile
      target: installer
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/apps/app1/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - ./apps/app1:/usr/src/app/apps/app1
    command: ["yarn", "start:dev"]
    # command: "tail -f /dev/null"
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`myapp.localhost`) && PathPrefix(`/app1`)"
      - "traefik.http.services.app1.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.prefixes=/app1"
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.forceslash=false"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.app1.middlewares=cors,app1-stripprefix"

  app1_dapr:
    image: "daprio/daprd:1.14.4"
    command: [
        "./daprd",
        "--app-id",
        "app1",
        "--app-port",
        "3000",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--config",
        "/dapr/config.yaml",
        "--resources-path",
        "/dapr/local",
      ]
    volumes:
      - "./volumes/infra/dapr/components:/dapr"
    depends_on:
      - app1
    network_mode: "service:app1"
    env_file:
      - .env
    logging: *default-logging

  ##### App2 & DAPR Sidecar #####
  app2:
    build:
      context: .
      dockerfile: ./apps/app2/Dockerfile
      target: installer
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - /usr/src/app/apps/app2/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - ./apps/app2:/usr/src/app/apps/app2
    command: ["yarn", "start:dev"]
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`myapp.localhost`) && PathPrefix(`/app2`)"
      - "traefik.http.services.app2.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.app2-stripprefix.stripprefix.prefixes=/app2"
      - "traefik.http.middlewares.app2-stripprefix.stripprefix.forceslash=false"
      - "traefik.http.routers.app2.middlewares=app2-stripprefix"

  app2_dapr:
    image: "daprio/daprd:1.14.4"
    command:
      [
        "./daprd",
        "-app-id",
        "app2",
        "-app-port",
        "3000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/local",
      ]
    volumes:
      - "./volumes/infra/dapr/components:/dapr"
    depends_on:
      - app2
    network_mode: "service:app2"
    env_file:
      - .env
    logging: *default-logging

  ##### App3 & DAPR Sidecar #####
  app3:
    build:
      context: .
      dockerfile: ./apps/app3/Dockerfile
      target: installer
    env_file:
      - .env
    ports:
      - "3002:3000"
    volumes:
      - /usr/src/app/apps/app3/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - ./apps/app3:/usr/src/app/apps/app3
    command: ["yarn", "start:dev"]
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app3.rule=Host(`myapp.localhost`) && PathPrefix(`/app3`)"
      - "traefik.http.services.app3.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.app3-stripprefix.stripprefix.prefixes=/app3"
      - "traefik.http.middlewares.app3-stripprefix.stripprefix.forceslash=false"
      - "traefik.http.routers.app3.middlewares=app3-stripprefix"

  app3_dapr:
    image: "daprio/daprd:1.14.4"
    command:
      [
        "./daprd",
        "-app-id",
        "app3",
        "-app-port",
        "3000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/local",
      ]
    volumes:
      - "./volumes/infra/dapr/components:/dapr"
    depends_on:
      - app3
    network_mode: "service:app3"
    env_file:
      - .env
    logging: *default-logging

networks:
  default:
    name: dapr_network
    external: true
