services:
  dapr_placement: # this is needed for workflow engine to work
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"

  ##### Traefik #####
  traefik:
    image: "traefik:v3.1"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # have to put traefik.enabled=true explicitly
      # - "--entryPoints.web.address=:80"
      - "--entryPoints.ws.address=:3000"
    ports:
      - "80:80"
      - "3000:3000"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ##### Rabbitmq #####
  rabbitmq:
    image: "rabbitmq:3.9-management"
    environment:
      - RABBITMQ_DEFAULT_USER=demo # these 2 env vars don't do anything because of `volumes/infra/rabbitmq/definitions.json` but it creates the same user
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie_1234
    volumes:
      - ./volumes/infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./volumes/infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./volumes/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  ##### Redis #####
  redis:
    image: "redis:6.2-alpine"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./volumes/data/infra/redis:/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - 8080:8080
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: "--wal_level=logical"
    volumes:
      - ./volumes/data/postgres:/var/lib/postgresql/data
      - ./volumes/infra/postgres:/docker-entrypoint-initdb.d:ro

  debezium:
    image: quay.io/debezium/server:3.0.1.Final
    ports:
      - "9090:8080"
    volumes:
      - ./volumes/infra/debezium:/debezium/config:ro

networks:
  default:
    name: k8s_playground_network
    driver: bridge
    external: true
