services:
  orders-svc:
    build:
      context: .
      dockerfile: ./apps/orders-svc/Dockerfile
      target: installer
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}orders
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
    volumes:
      - /usr/src/app/apps/orders-svc/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - /usr/src/app/apps/orders-svc/generated
      - ./apps/orders-svc:/usr/src/app/apps/orders-svc
    command: ["yarn", "start:dev"]
    # command: "tail -f /dev/null"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders-svc.rule=Host(`myapp.localhost`) && PathPrefix(`/orders`)"
      - "traefik.http.routers.orders-svc.entrypoints=web"
      - "traefik.http.services.orders-svc.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.orders-svc-stripprefix.stripprefix.prefixes=/orders"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.orders-svc.middlewares=cors,orders-svc-stripprefix"

  cart-svc:
    build:
      context: .
      dockerfile: ./apps/cart-svc/Dockerfile
      target: installer
    ports:
      - "3004:3000"
      - "9239:9229"
    environment:
      - DATABASE_URL=${DATABASE_URL}cart
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    volumes:
      - /usr/src/app/apps/cart-svc/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - /usr/src/app/apps/cart-svc/generated
      - ./apps/cart-svc:/usr/src/app/apps/cart-svc
    command: ["yarn", "start:dev"]
    # command: ["yarn", "start:debug"]
    # command: "tail -f /dev/null"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cart-svc.rule=Host(`myapp.localhost`) && PathPrefix(`/cart`)"
      - "traefik.http.routers.cart-svc.entrypoints=web"
      - "traefik.http.services.cart-svc.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.cart-svc-stripprefix.stripprefix.prefixes=/cart"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.cart-svc.middlewares=cors,cart-svc-stripprefix"

  inventory-svc:
    build:
      context: .
      dockerfile: ./apps/inventory-svc/Dockerfile
      target: installer
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}inventory
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /usr/src/app/apps/inventory-svc/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - /usr/src/app/apps/inventory-svc/generated
      - ./apps/inventory-svc:/usr/src/app/apps/inventory-svc
    command: ["yarn", "start:dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventory-svc.rule=Host(`myapp.localhost`) && PathPrefix(`/inventory`)"
      - "traefik.http.routers.inventory-svc.entrypoints=web"
      - "traefik.http.services.inventory-svc.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.inventory-svc-stripprefix.stripprefix.prefixes=/inventory"
      - "traefik.http.routers.inventory-svc.middlewares=inventory-svc-stripprefix"

  users-svc:
    build:
      context: .
      dockerfile: ./apps/users-svc/Dockerfile
      target: installer
    ports:
      - "3002:3000"
      - "9229:9229"
    environment:
      - DATABASE_URL=${DATABASE_URL}users
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_CLIENTID}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
    volumes:
      - /usr/src/app/apps/users-svc/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - /usr/src/app/apps/users-svc/generated
      - ./apps/users-svc:/usr/src/app/apps/users-svc
      - ./packages:/usr/src/app/packages
    # command: ["yarn", "start:dev"]
    command: ["yarn", "start:debug"]
    # command: "tail -f /dev/null"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-svc.rule=Host(`myapp.localhost`) && PathPrefix(`/users`)"
      - "traefik.http.routers.users-svc.entrypoints=web"
      - "traefik.http.services.users-svc.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.users-svc-stripprefix.stripprefix.prefixes=/users"
      - "traefik.http.routers.users-svc.middlewares=users-svc-stripprefix"

  notifications-svc:
    build:
      context: .
      dockerfile: ./apps/notifications-svc/Dockerfile
      target: installer
    ports:
      - "3003:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    volumes:
      - /usr/src/app/apps/notifications-svc/node_modules # dont overwrite node_modules inside container (some packages need to be built for specific platform, so they might be broken if they are mounted, more info on this syntax - https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder/37898591#37898591)
      - /usr/src/app/apps/notifications-svc/generated
      - ./apps/notifications-svc:/usr/src/app/apps/notifications-svc
    command: ["yarn", "start:dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifications-svc.rule=Host(`myapp.localhost`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.notifications-svc.entrypoints=web"
      - "traefik.http.services.notifications-svc.loadbalancer.server.port=3000"

  temporal-worker:
    build:
      context: .
      dockerfile: ./apps/temporal-worker/Dockerfile
    environment:
      - ORDERS_SVC_URL=${ORDERS_SVC_URL}
      - TEMPORAL_HOST=${TEMPORAL_HOST}

networks:
  default:
    name: k8s_playground_network
    external: true
