serviceName: notifications
port: 3000
env:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_USER: default
envRaw:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: REDIS_PASSWORD
