serviceName: users-svc
port: 3000
migrationsEnabled: true
env:
  KEYCLOAK_URL: http://keycloak-service:8080 # name of keycloak service that exposes this port
  KEYCLOAK_REALM: test_realm
  DB_HOST: postgres
  DB_PORT: 5432
  DB_SCHEMA: orders
  KAFKA_BROKERS: kafka:9092
envRaw:
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: postgres.postgres.credentials.postgresql.acid.zalan.do
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres.postgres.credentials.postgresql.acid.zalan.do
        key: password
  - name: DATABASE_URL # add it last, so it can reference previous env vars
    value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/postgres?schema=$(DB_SCHEMA)
  - name: KEYCLOAK_SECRET
    valueFrom:
    secretKeyRef:
      name: keycloak-client-secret
      key: CONFIDENTIAL_CLIENT_SECRET
