serviceName: app1
port: 3000
env:
  KEYCLOAK_URL: http://keycloak-service:8080 # name of keycloak service that exposes this port
  KEYCLOAK_REALM: test_realm
  KEYCLOAK_CLIENTID: test_client_confidential
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  DB_HOST: postgres
  DB_PORT: 5432
  DB_SCHEMA: orders
envRaw:
  - name: KEYCLOAK_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-client-secret
        key: CONFIDENTIAL_CLIENT_SECRET
  - name: APP_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: dapr-api-token
        key: dapr-api-token
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: RABBITMQ_PASSWORD
  - name: RABBITMQ_USER
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: RABBITMQ_USER
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: PG_USER
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: PG_PASSWORD
  - name: DATABASE_URL # add it last, so it can reference previous env vars
    value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/postgres?schema=$(DB_SCHEMA)
