apiVersion: v1
kind: Service
metadata:
  name: myapp-app1
  labels:
    name: myapp-app1-service
    app: myapp
    type: backend
spec:
  selector:
    name: myapp-app1-pod
    app: myapp
    type: backend
  ports:
    - port: 3000
      targetPort: 3000
