apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    name: app1-service
    app: myapp
    type: backend
spec:
  selector:
    name: app1-pod
    app: myapp
    type: backend
  ports:
    - port: 3000
      targetPort: 3000
