apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    name: app2-service
    app: myapp
    type: backend
spec:
  selector:
    name: app2-pod
    app: myapp
    type: backend
  ports:
    - port: 3001
      targetPort: 3000
