apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deploy
  labels:
    name: app2-deploy
    app: myapp
    type: backend
spec:
  selector:
    matchLabels:
      name: app2-pod
      app: myapp
      type: backend
  template:
    metadata:
      name: app2-pod
      labels:
        name: app2-pod
        app: myapp
        type: backend
    spec:
      containers:
        - name: app2
          # build with `docker build -t k8s_playground-app2 . -f apps/app2/Dockerfile` followed by `minikube image load k8s_playground-app2`
          # https://stackoverflow.com/a/42564211/3697384 (build image with Minikube's docker daemon)
          image: k8s_playground-app2
          imagePullPolicy: Never
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: envvar-configmap
        - name: app2-dapr
          image: daprio/daprd:1.14.4
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          command: [
              "./daprd",
              "--app-id",
              "app2",
              "--app-port",
              "3000",
              "--placement-host-address",
              "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
              "--config",
              "/dapr/config.yaml",
              "--resources-path",
              "/dapr/local",
            ]
          env:
            - name: APP_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: envvar-configmap
                  key: APP_API_TOKEN
          volumeMounts:
            - name: dapr-local-volume
              mountPath: /dapr/local
            - name: dapr-volume
              mountPath: /dapr/config.yaml
              subPath: config.yaml
          # annotations:
          #   dapr.io/enabled: "true"
          #   dapr.io/app-id: "myapp"
          #   dapr.io/app-protocol: "grpc"
          #   dapr.io/app-port: "5005"
      volumes:
        - name: dapr-volume
          configMap:
            name: dapr-configmap
            items:
              - key: config.yaml
                path: config.yaml
        - name: dapr-local-volume
          configMap:
            name: dapr-local-configmap
