apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deploy
  labels:
    name: notifications-deploy
    app: myapp
    type: backend
spec:
  selector:
    matchLabels:
      name: notifications-pod
      app: myapp
      type: backend
  template:
    metadata:
      name: notifications-pod
      labels:
        name: notifications-pod
        app: myapp
        type: backend
    spec:
      containers:
        - name: notifications
          # build with `docker build -t k8s_playground-notifications . -f apps/notifications/Dockerfile` followed by `minikube image load k8s_playground-notifications`
          # https://stackoverflow.com/a/42564211/3697384 (build image with Minikube's docker daemon)
          image: k8s_playground-notifications
          imagePullPolicy: Never
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 3000
