apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: myapp
    type: infra
spec:
  selector:
    matchLabels:
      name: postgres-pod
      app: myapp
      type: infra
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: myapp
        type: infra
    spec:
      containers:
        - name: postgres
          image: postgres
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
    # TODO: mount init db files?
