apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  labels:
    name: postgres-nodeport-service
    app: myapp
    type: infra
spec:
  type: NodePort
  selector:
    name: postgres-pod
    app: myapp
    type: infra
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32345
