apiVersion: v1
kind: Service
metadata:
  name: postgres # this is name by which the service can be reached (ClusterIP) within cluster
  labels:
    name: postgres-service
    app: myapp
    type: infra
spec:
  selector:
    name: postgres-pod
    app: myapp
    type: infra
  ports:
    - port: 5432
      targetPort: 5432
