apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # this is name by which the service can be reached (ClusterIP) within cluster
  labels:
    name: rabbitmq-internal-service
    app: myapp
    type: infra
spec:
  selector:
    name: rabbitmq-pod
    app: myapp
    type: infra
  ports:
    - port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  labels:
    name: rabbitmq-nodeport-service
    app: myapp
    type: infra
spec:
  type: NodePort
  selector:
    name: rabbitmq-pod
    app: myapp
    type: infra
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30008
