apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  labels:
    name: rabbitmq-nodeport-service
    app: myapp
    type: infra
spec:
  type: NodePort
  selector:
    name: rabbitmq-pod
    app: myapp
    type: infra
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30008
