kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/myapp/rabbitmq-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
