apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    name: rabbitmq-deploy
    app: myapp
    type: infra
spec:
  selector:
    matchLabels:
      name: rabbitmq-pod
      app: myapp
      type: infra
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        name: rabbitmq-pod
        app: myapp
        type: infra
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9-management
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 15672
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "demo"
            - name: RABBITMQ_DEFAULT_PASS
              value: "demo"
            - name: RABBITMQ_ERLANG_COOKIE
              value: "demo_cookie_1234"
