apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: myapp
    type: infra
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: myapp
      type: infra
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: myapp
        type: infra
    spec:
      containers:
        - name: redis
          image: redis
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-pv-storage
              mountPath: "/data"
      volumes:
        - name: redis-volume
          configMap:
            name: redis-configmap
        - name: redis-pv-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim
