apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: myapp
    type: infra
spec:
  selector:
    name: redis-pod
    app: myapp
    type: infra
  ports:
    - port: 6379
      targetPort: 6379
