apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: myapp
    type: infra
spec:
  containers:
    - name: redis
      image: redis
      # resources:
      #   limits:
      #     memory: "128Mi"
      #     cpu: "500m"
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-volume
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
  volumes:
    - name: redis-volume
      configMap:
        name: redis-configmap
