apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  labels:
    name: traefik-dashboard-service
    app: myapp
    type: infra
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    name: traefik-pod
    app: myapp
    type: infra
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  labels:
    name: traefik-web-service
    app: myapp
    type: infra
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    name: traefik-pod
    app: myapp
    type: infra
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ws-service
  labels:
    name: traefik-ws-service
    app: myapp
    type: infra
spec:
  type: LoadBalancer
  ports:
    - targetPort: ws
      port: 3000
  selector:
    name: traefik-pod
    app: myapp
    type: infra
