apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-deploy
  labels:
    name: {{ .Values.serviceName }}-deploy
{{- include "backend-app.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.serviceName }}-pod
{{- include "backend-app.labels" . | indent 6 }}
  template:
    metadata:
      name: {{ .Values.serviceName }}-pod
      labels:
        name: {{ .Values.serviceName }}-pod
{{- include "backend-app.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: k8s_playground-{{ .Values.serviceName }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.port }}
          {{- include "env" . | indent 10}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.serviceName }}-ingress-route
  labels:
    name: {{ .Values.serviceName }}-ingress-route
{{- include "backend-app.labels" . | indent 4 }}
spec:
  entryPoints:
    - ws
  routes:
    - match: PathPrefix("/") # match everything
      kind: Rule
      services:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.port }}
---
{{ include "app.service" . }}
