serviceName: notifications-svc
routePrefix: socket.io
keepPrefix: true # for example: /socket.io/?EIO=4&transport=websocket
port: 3000
env:
  KEYCLOAK_URL: http://keycloak-service:8080 # name of keycloak service that exposes this port
  KEYCLOAK_REALM: test_realm
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_USER: default
envRaw:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: password
