serviceName: notifications-svc
port: 3000
env:
  KEYCLOAK_URL: http://keycloak-service:8080 # name of keycloak service that exposes this port
  KEYCLOAK_REALM: test_realm
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_USER: default
envRaw:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: debezium-secret
        key: REDIS_PASSWORD
