{{- define "dapr-app.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-deploy
  labels:
    name: {{ .Values.serviceName }}-deploy
    {{- include "backend-app.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.serviceName }}-pod
      {{- include "backend-app.labels" . | indent 6 }}
  template:
    metadata:
      name: {{ .Values.serviceName }}-pod
      labels:
        name: {{ .Values.serviceName }}-pod
        {{- include "backend-app.labels" . | indent 8 }}
      annotations:
        {{- include "dapr.annotations" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: k8s_playground-{{ .Values.serviceName }}
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          {{- if (.Values.envFrom)}}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 -}}
          {{ end }}
          {{- if (.Values.env)}}
          env:
            {{- range $k,$v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{ end }}
{{- end }}
