{{- define "app.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-deploy
  labels:
    name: {{ .Values.serviceName }}-deploy
    {{- include "backend-app.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.serviceName }}-pod
      {{- include "backend-app.labels" . | indent 6 }}
  template:
    metadata:
      name: {{ .Values.serviceName }}-pod
      labels:
        name: {{ .Values.serviceName }}-pod
        {{- include "backend-app.labels" . | indent 8 }}
    {{- if .Values.annotations }}
      annotations:
      {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      {{- if .Values.migrationsEnabled }}
      initContainers:
        - name: {{ .Values.serviceName }}-db-migrations
          image: k8s_playground-{{ .Values.serviceName }}-migration
          imagePullPolicy: Never
          command: [ 'yarn', 'prisma', 'migrate', 'deploy' ]
          {{- include "env" . | indent 10}}
      {{- end }}
      containers:
        - name: {{ .Values.serviceName }}
          image: k8s_playground-{{ .Values.serviceName }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.port }}
          {{- include "env" . | indent 10}}
{{- end }}
