{{ define "app.ingressroute" }}
{{ if not .Values.keepPrefix }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.serviceName }}-stripprefix-middleware
spec:
  stripPrefix:
    prefixes:
      - /{{ .Values.routePrefix }}
---
{{ end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.serviceName }}-ingress-route
  labels:
    name: {{ .Values.serviceName }}-ingress-route
    {{- include "backend-app.labels" . | indent 4 }}
spec:
  entryPoints:
    - web # same as args in traefik deployment
  routes:
    - match: PathPrefix(`/{{ .Values.routePrefix }}`)
      kind: Rule
      services:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.port }}
      middlewares:
        - name: cors-middleware
        {{- if .Values.stripPrefix }}
        - name: {{ .Values.serviceName }}-stripprefix-middleware
        {{- end }}
{{ end }}
