apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: dapr
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
  metric:
    enabled: true
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorbackend
  namespace: dapr
spec:
  type: workflowbackend.actor
  version: v1
  metadata:
    - name: actorIdleTimeout
      value: "5m"
    - name: actorScanInterval
      value: "30s"
    - name: drainOngoingCallTimeout
      value: "1m"
    - name: drainRebalancedActors
      value: true
---
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: app1-to-app2-resiliency
  namespace: dapr
scopes:
  - app1
spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 1s
        maxRetries: -1
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        trip: consecutiveFailures >= 3
  targets:
    apps:
      app2:
        retry: retryForever
        # circuitBreaker: simpleCB
---

