apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: myapp
spec:
  teamId: myapp
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    # database owner
    postgres:
      - superuser
      - createdb
    # foo_user: []  # role for application foo
  #databases: name->owner
  databases:
    postgres: postgres
  postgresql:
    version: "16"
    parameters:
      password_encryption: "scram-sha-256"
      wal_level: "logical" # needed for Debezium log trailing
      # log slow queries
      log_statement: "all"
      log_duration: "on"
      log_min_duration_statement: "1s" # configure this as needed
      pg_store_plans.plan_format: "json"
      pg_store_plans.max_plan_length: "1048576"
      pg_store_plans.log_analyze: "true"
      pg_store_plans.log_buffers: "true"
      pg_store_plans.log_timing: "true"
