apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: myapp
# https://www.rabbitmq.com/kubernetes/operator/using-operator
spec:
  replicas: 1 # use odd number
  persistence:
    storage: 10Gi
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: rabbitmq-users-exchange
  namespace: myapp
spec:
  name: users
  # type: fanout # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: rabbitmq-users-queue
  namespace: myapp
spec:
  name: users # name of the queue
  type: stream # without providing a queue type, rabbitmq creates a classic queue
  durable: true # mandatory for stream queues
  arguments:
    x-max-length-bytes: 1000000000 ## setting the retention policy
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitmq-users-binding
  namespace: myapp
spec:
  source: users # an existing exchange
  destination: users # an existing queue
  destinationType: queue # can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: rabbitmq
