apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: myapp
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: rabbitmq-users-exchange
  namespace: myapp
spec:
  name: users
  # type: fanout # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq # name of RabbitmqCluster?
---
# apiVersion: rabbitmq.com/v1beta1
# kind: Binding
# metadata:
#   name: binding
#   namespace: rabbitmq-system
# spec:
#   source: test # an existing exchange
#   destination: test # an existing queue
#   destinationType: queue # can be 'queue' or 'exchange'
#   rabbitmqClusterReference:
#     name: example-rabbit

