# https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/charts/redis/templates/redis-standalone.yaml
# redis-standalone.yaml with in-place variables from values.yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: redis
  labels:
    name: redis
    app: myapp
    type: infra
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis
    imagePullPolicy: Always
    redisSecret:
      name: redis-secret
      key: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ext-config
data:
  redis-additional.conf: |
    loglevel notice
    maxclients 100
    tcp-keepalive 400
    slowlog-max-len 158
    stream-node-max-bytes 2048
---
apiVersion: v1
kind: Service
metadata:
  name: redis-external-service
  namespace: redis
  annotations:
    name: redis-external-service
    app: myapp
    type: infra
spec:
  type: NodePort
  selector:
    name: redis
    app: myapp
    type: infra
    redis_setup_type: standalone
    role: standalone
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: client
---
# This file is for demo purposes only
# Secrets should be configured another way
# TODO:
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  password: somepassword
