apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: users_binding
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: route
      value: /dapr/users
    - name: queueName
      value: "users"
    - name: host
      value: "amqp://demo:demo@rabbitmq:5672"
    - name: durable
      value: "true"
    - name: deleteWhenUnused
      value: "false"
    # - name: ttlInSeconds
    #   value: "60"
    # - name: prefetchCount
    #   value: "0"
    # - name: exclusive
    #   value: "false"
    # - name: maxPriority
    #   value: "5"
    # - name: contentType
    #   value: "text/plain"
    # - name: reconnectWaitInSeconds
    #   value: "5"
    # - name: externalSasl
    #   value: "false"
    # - name: caCert
    #   value: "null"
    # - name: clientCert
    #   value: "null"
    # - name: clientKey
    #   value: "null"
    - name: direction
      value: "input"
scopes:
  - app1
