apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      secretKeyRef:
        name: redisPassword
        key: redisPassword
    - name: actorStateStore # Required for workflow engine
      value: "true"
auth:
  secretStore: localsecrets
