apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: app1_to_app2-resiliency
scopes:
  - app1
spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 1s
        maxRetries: -1
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        trip: consecutiveFailures >= 3
  targets:
    apps:
      app2:
        retry: retryForever
        # circuitBreaker: simpleCB
