apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: orders-svc-to-inventory-svc-resiliency
scopes:
  - orders-svc
spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 1s
        maxRetries: -1
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        trip: consecutiveFailures >= 3
  targets:
    apps:
      inventory-svc:
        retry: retryForever
        # circuitBreaker: simpleCB
